### ISSUE TITLE
KeyValueStore requires a network

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#13]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#544
From: @cxbrooks
Reported version: unspecified
CC:   accessors-devel@terraswarm.org

**Comment by cxbrooks** [comment]
Edward reported:

"The key-value store server doesn't work if wifi is turned off or is
not connected to an access point. It seems that, at least on a mac,
localhost is not accessible in this case... ???"

When I run
$PTII/bin/capecode ./ptolemy/actor/lib/jjs/modules/httpServer/demo/KeyValueStoreClient/KeyValueStoreClient.xml

I see the following on stdout:

Sep 25, 2017 12:59:00 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,1,main] has been blocked for 10075 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        at sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:140)
        at sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
...

Sep 25, 2017 12:59:00 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 8f:73:c6:b8:e7:b7:70:70

https://github.com/netty/netty/issues/6406 suggests updating netty.
