### ISSUE TITLE
Exceptions when you open the MoreLibraries folder on the left  - ptolemy.data.properties.lattice.PropertyConstraintSolver

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#140]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#208
From: Bert Rodiers &lt;<bert.rodiers@gmail.com>&gt;
Reported version: 7.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
First exception:
java.lang.NullPointerException
	at ptolemy.data.properties.lattice.PropertyConstraintSolver._addChoices(PropertyConstraintSolver.java:630)
	at ptolemy.data.properties.lattice.PropertyConstraintSolver.<init>(PropertyConstraintSolver.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at ptolemy.moml.MoMLParser._createInstance(MoMLParser.java:4038)
	at ptolemy.moml.MoMLParser._handlePropertyElement(MoMLParser.java:5122)
	at ptolemy.moml.MoMLParser.startElement(MoMLParser.java:2831)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:931)
	at com.microstar.xml.XmlParser.parseContent(XmlParser.java:1104)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:924)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1381)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1338)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1493)
	at ptolemy.moml.EntityLibrary.populate(EntityLibrary.java:495)
	at ptolemy.moml.EntityLibrary.classDefinitionList(EntityLibrary.java:292)
	at ptolemy.moml.EntityLibrary.getConfigureText(EntityLibrary.java:405)
	at ptolemy.moml.MoMLParser.endElement(MoMLParser.java:763)
	at com.microstar.xml.XmlParser.parseETag(XmlParser.java:1026)
	at com.microstar.xml.XmlParser.parseContent(XmlParser.java:1098)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:924)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1381)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1338)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1300)
	at ptolemy.moml.MoMLParser._parse(MoMLParser.java:5525)
	at ptolemy.moml.MoMLParser.startElement(MoMLParser.java:2618)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:931)
	at com.microstar.xml.XmlParser.parseContent(XmlParser.java:1104)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:924)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1381)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1338)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1300)
	at ptolemy.moml.MoMLParser._parse(MoMLParser.java:5525)
	at ptolemy.moml.MoMLParser.startElement(MoMLParser.java:2618)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:931)
	at com.microstar.xml.XmlParser.parseContent(XmlParser.java:1104)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:924)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1381)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1338)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1493)
	at ptolemy.moml.EntityLibrary.populate(EntityLibrary.java:495)
	at ptolemy.moml.EntityLibrary.attributeList(EntityLibrary.java:220)
	at ptolemy.vergil.tree.VisibleTreeModel._attributes(VisibleTreeModel.java:135)
	at ptolemy.vergil.tree.FullTreeModel.getChildCount(FullTreeModel.java:112)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1461)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1270)
	at javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:966)
	at javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:164)
	at javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:1648)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:3721)
	at javax.swing.JTree.fireTreeExpanded(JTree.java:2659)
	at javax.swing.JTree.setExpandedState(JTree.java:3430)
	at javax.swing.JTree.expandPath(JTree.java:2166)
	at javax.swing.plaf.basic.BasicTreeUI.toggleExpandState(BasicTreeUI.java:2209)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2318)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3517)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3456)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:262)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6038)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3265)
	at java.awt.Component.processEvent(Component.java:5806)
	at java.awt.Container.processEvent(Container.java:2058)
	at java.awt.Component.dispatchEventImpl(Component.java:4413)
	at java.awt.Container.dispatchEventImpl(Container.java:2116)
	at java.awt.Component.dispatchEvent(Component.java:4243)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4322)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3983)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3916)
	at java.awt.Container.dispatchEventImpl(Container.java:2102)
	at java.awt.Window.dispatchEventImpl(Window.java:2440)
	at java.awt.Component.dispatchEvent(Component.java:4243)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)

**Comment by cxbrooks** [comment]
After a clean build, I can't reproduce this.
Can you try a clean build.

BTW - we don't usually introduce bug reports for one-off transitory problems
like this or problems in the build.  Usually I don't add a bug report until
a day or two after something was reported.  The primary reason is to reduce
the amount of adminstrivia.  I guess this is just part of our local culture.

**Comment by cxbrooks** [comment]
I'm closing this because it works for me.  I tried it under both
Windows and the Mac.

The copyright facility includes a way to automatically expand the actor
library tree on the left.  That test worked, though there were
minor problems with x10 because it is not installed.

To run the copyright tests, click on the Copyright link and then 
click through the pages until the about:expandLibrary link comes up.
