### ISSUE TITLE
exportMoML() does not support level crossing links

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#149]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#217
From: @cxbrooks
Reported version: 7.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

Blocker for:  [BZ#165](https://github.com/cxbrooks/test/issues?q=is%3Aissue%20%22Original%20bug%20ID%3A%20BZ%23165%22)

**Comment by cxbrooks** [comment]
Created attachment 24
Tcl test that illustrates problem with exportMoML and level crossing links

If I create a model that has an inner transparent composite that has an actor
with a level crossing link to an actor in the top level, then the model
runs, and exporting the moml works, but trying to reload the moml fails because
the inner composite is parsed first and it refers to a relation in the top
level that does not yet exist.

The parse fails with:
com.microstar.xml.XmlException: No relation named ".top._R" in .top.e1 in file:/Users/cxh/ptII/ptolemy/moml/test/ at line 51 and column 8
	at ptolemy.moml.MoMLParser._checkForNull(MoMLParser.java:3685)
	at ptolemy.moml.MoMLParser._processLink(MoMLParser.java:5842)
	at ptolemy.moml.MoMLParser.access$700(MoMLParser.java:204)
	at ptolemy.moml.MoMLParser$LinkRequest.execute(MoMLParser.java:6899)
	at ptolemy.moml.MoMLParser._processPendingRequests(MoMLParser.java:6010)
	at ptolemy.moml.MoMLParser.endElement(MoMLParser.java:911)

The offending line is:
       <link port="ramp.output" relation=".top._R"/>

The problem is that the relation is not declared until the very end:
    <link port="rec.input" relation="_R"/>

I also tried placing the relation inside the inner composite:
 $e1 connect \
	    [java::field [java::cast ptolemy.actor.lib.Source $ramp] output] \
            [java::field [java::cast ptolemy.actor.lib.Sink $rec] input]
and that failed with:

while executing
com.microstar.xml.XmlException: No relation named ".top.e1._R" in .top in file:/Users/cxh/ptII/ptolemy/moml/test/ at line 65 and column 4

If I take the output and change:
  <link port="rec.input" relation=".top.e1._R"/>
to
  <link port="rec.input" relation="e1._R"/>

ptolemy.kernel.util.IllegalActionException: Link crosses levels of the hierarchy
  in .top.rec.input and .top.e1._R

So, it appears that there is no way for MoML to represent models that have
level crossing links?

> Attached file: [LevelXing.tcl](https://coq.inria.fr/bugfiles/attachment.cgi?id=24) (application/octet-stream, 1206 bytes)
> Description:   Tcl test that illustrates problem with exportMoML and level crossing links

**Comment by cxbrooks** [comment]
Created attachment 25
MoML file with level crossing link

This file was created by the test case and has a level crossing link.
It fails to parse.

> Attached file: [LevelCrossingLink.xml](https://coq.inria.fr/bugfiles/attachment.cgi?id=25) (text/xml, 3232 bytes)
> Description:   MoML file with level crossing link

**Comment by cxbrooks** [comment]
Edward suggests a solution:

1) MoMLParser needs to detect when a link crosses levels and use the
liberalLink method instead of the link() method. 
 
2) When exporting MoML a level crossing link needs to be exported at
the lowest common container (or the top level?).  The idea is that
the level crossing link is created after the two ports and their
containers are created.

Edward proposes this MoML file as an example of the solution:

?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="foo" class="ptolemy.kernel.CompositeEntity">
  <entity name="A" class="ptolemy.kernel.CompositeEntity">
    <entity name="Ramp" class="ptolemy.kernel.CompositeEntity">
      <port name="P" class="ptolemy.kernel.ComponentPort"/>
    </entity>
  </entity>
  <entity name="B" class="ptolemy.kernel.CompositeEntity">
    <entity name="Ramp" class="ptolemy.kernel.CompositeEntity">
      <port name="P" class="ptolemy.kernel.ComponentPort"/>
    </entity>
  </entity>
  <relation name="R" class="ptolemy.kernel.ComponentRelation"/>
  <link port="A.Ramp.P" relation="R"/>
  <link port="B.Ramp.P" relation="R"/>
</entity>

**Comment by cxbrooks** [comment]
Making this P1 so that models can be partially parsed and stored, which will
improve startup time.

**Comment by cxbrooks** [comment]
Edward wrote:
    I've just checked in a change to ptolemy.kernel.ComponentPort
    so that a MoML file with level-crossing links can be read correctly.
    Specifcally, MoML files like the one attached can now be opened
    in Vergil.

    Note that once it is opened, there are some issues:

     1) The level-crossing links are not shown.
     2) If you save it, the resulting MoML is incorrect and cannot be
    re-opened.

    I'll address problem (2) next.  I'm not sure what to do about
    problem 1.  Probably we need some sort of visual indication
    that there is a level-crossing link there.  Perhaps it should
    show the full name of the destination?

**Comment by cxbrooks** [comment]
Marking this as assigned, can we close it?

**Comment by cxbrooks** [comment]
exportMoML() has supported level crossing links for some time.
I updated moml/test/LevelCrossingLinkTest.tcl to illustrate this fact.
