### ISSUE TITLE
SDF HTVQ Demo throws a NullPointerException

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#160]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#229
From: Hiren D. Patel &lt;<hiren@eecs.berkeley.edu>&gt;
Reported version: 7.1.devel
CC:   bert.rodiers@gmail.com, pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
1. Open the demo example ptolemy/domains/sdf/demo/HTVQ/HTVQ.xml
2. Run it.
3. Stack trace
ptolemy.kernel.util.IllegalActionException: Problem reading codebook
  in .HTVQ.Encoder
Because:
java.lang.NullPointerException
	at ptolemy.domains.sdf.lib.vq.HTVQEncode.initialize(HTVQEncode.java:287)
	at ptolemy.actor.Director.initialize(Director.java:722)
	at ptolemy.actor.Director.initialize(Director.java:695)
	at ptolemy.domains.sdf.kernel.SDFDirector.initialize(SDFDirector.java:421)
	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:666)
	at ptolemy.actor.Manager.initialize(Manager.java:619)
	at ptolemy.actor.Manager.execute(Manager.java:338)
	at ptolemy.actor.Manager.run(Manager.java:1138)
	at ptolemy.actor.Manager$3.run(Manager.java:1179)
Caused by: java.lang.NullPointerException
	at ptolemy.domains.sdf.lib.vq.HTVQEncode._fullRead(HTVQEncode.java:476)
	at ptolemy.domains.sdf.lib.vq.HTVQEncode.initialize(HTVQEncode.java:264)
	... 8 more
Caused by: java.lang.NullPointerException
	at ptolemy.domains.sdf.lib.vq.HTVQEncode._fullRead(HTVQEncode.java:476)
	at ptolemy.domains.sdf.lib.vq.HTVQEncode.initialize(HTVQEncode.java:264)
	at ptolemy.actor.Director.initialize(Director.java:722)
	at ptolemy.actor.Director.initialize(Director.java:695)
	at ptolemy.domains.sdf.kernel.SDFDirector.initialize(SDFDirector.java:421)
	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:666)
	at ptolemy.actor.Manager.initialize(Manager.java:619)
	at ptolemy.actor.Manager.execute(Manager.java:338)
	at ptolemy.actor.Manager.run(Manager.java:1138)
	at ptolemy.actor.Manager$3.run(Manager.java:1179)

**Comment by cxbrooks** [comment]
Fixed by using $CLASSPATH in the path for the code book.
