### ISSUE TITLE
selecting and deleting a PortParameter gives error

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#193]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#311
From: Derik Barseghian &lt;<barseghian@nceas.ucsb.edu>&gt;
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
This happens in Vergil and Kepler. If you click and select an area around a PortParameter to select it (and in Vergil also a FilePortParameter) and then click your backspace/delete key, you'll get an error like the below (the below is the Kepler version). However if you just click directly on the PortParameter to select it and then delete it, this doesn't happen.

om.microstar.xml.XmlException: No such property: PortParameter in .Unnamed1 in [external stream] at line 4 and column 4
	at ptolemy.moml.MoMLParser._searchForAttribute(MoMLParser.java:6703)
	at ptolemy.moml.MoMLParser._deleteProperty(MoMLParser.java:4546)
	at ptolemy.moml.MoMLParser.access$5(MoMLParser.java:4545)
	at ptolemy.moml.MoMLParser$DeleteRequest.execute(MoMLParser.java:7182)
	at ptolemy.moml.MoMLParser._processPendingRequests(MoMLParser.java:6339)
	at ptolemy.moml.MoMLParser.endElement(MoMLParser.java:893)
	at com.microstar.xml.XmlParser.parseETag(XmlParser.java:1026)
	at com.microstar.xml.XmlParser.parseContent(XmlParser.java:1098)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:924)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1403)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1375)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1531)
	at ptolemy.moml.MoMLChangeRequest._execute(MoMLChangeRequest.java:270)
	at ptolemy.kernel.util.ChangeRequest.execute(ChangeRequest.java:171)
	at ptolemy.kernel.util.NamedObj.executeChangeRequests(NamedObj.java:727)
	at ptolemy.kernel.util.NamedObj.requestChange(NamedObj.java:1751)
	at ptolemy.actor.CompositeActor.requestChange(CompositeActor.java:1503)

**Comment by cxbrooks** [comment]
Fixed.  Maybe.

The issue is that if I drag a region around a PortParameter,
the MoMLChangeRequest that it executed is:

<group>
<deletePort name="PortParameter"/>
<deleteProperty name="PortParameter"/>
</group>

The error occurs when we do the <deleteProperty...
because the property has already been deleted by the <deletePort ...

The reason this occurs is because both the ParameterPort and the
PortParameter are in selection when I drag a region
around a PortParameter.  The way to see this is to do the drag,
do a copy and then paste the contents into a text buffer.  I get:


<property name="PortParameter" class="ptolemy.actor.parameters.PortParameter">
    <property name="_hideName" class="ptolemy.kernel.util.SingletonAttribute">
    </property>
    <property name="_icon" class="ptolemy.vergil.icon.ValueIcon">
    </property>
    <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
        <configure>
      <svg>
	<polyline points="-15,-15, -3,-5, -16,5" style="stroke:black"></polyline>
	<polygon points="-22,-1, -22,4, -10,-5, -22,-14, -22,-9, -30,-9, -30, -1" style="fill:lightGray"></polygon>
      </svg>
    </configure>
    </property>
    <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
        <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:black" y="20">-P-</text>
      </svg>
    </configure>
    </property>
    <property name="_editorFactory" class="ptolemy.vergil.toolbox.VisibleParameterEditorFactory">
    </property>
    <property name="_location" class="ptolemy.kernel.util.Location" value="{190, 160}">
    </property>
</property>
<port name="PortParameter" class="ptolemy.actor.parameters.ParameterPort">
    <property name="input"/>
    <property name="_location" class="ptolemy.kernel.util.Location" value="{170.0, 155.0}">
    </property>
</port>

If I just click on the PortParameter, copy, then paste, I get:

<property name="PortParameter" class="ptolemy.actor.parameters.PortParameter">
    <property name="_hideName" class="ptolemy.kernel.util.SingletonAttribute">
    </property>
    <property name="_icon" class="ptolemy.vergil.icon.ValueIcon">
    </property>
    <property name="_iconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
        <configure>
      <svg>
	<polyline points="-15,-15, -3,-5, -16,5" style="stroke:black"></polyline>
	<polygon points="-22,-1, -22,4, -10,-5, -22,-14, -22,-9, -30,-9, -30, -1" style="fill:lightGray"></polygon>
      </svg>
    </configure>
    </property>
    <property name="_smallIconDescription" class="ptolemy.kernel.util.SingletonConfigurableAttribute">
        <configure>
      <svg>
        <text x="20" style="font-size:14; font-family:SansSerif; fill:black" y="20">-P-</text>
      </svg>
    </configure>
    </property>
    <property name="_editorFactory" class="ptolemy.vergil.toolbox.VisibleParameterEditorFactory">
    </property>
    <property name="_location" class="ptolemy.kernel.util.Location" value="{190, 160}">
    </property>
</property>



My fix was to modify BasicGraphFrame._deleteMoML() so that
if the actual object is a ParameterPort, then we don't generate
the <deletePort ...

This seems very funky.

One minor bug is that if I click on a PortParameter, copy, move the
original and then paste, then I get an extraneous Port arrow, which then
disappears if I move the PortParameter.

**Comment by cxbrooks** [comment]
This is happening to me again in the kepler and wrp suite.

**Comment by cxbrooks** [comment]
The stacktrace is:

com.microstar.xml.XmlException: No such property: PortParameter in .Unnamed1 in [external stream] at line 4 and column 4
	at ptolemy.moml.MoMLParser._searchForAttribute(MoMLParser.java:6703)
	at ptolemy.moml.MoMLParser._deleteProperty(MoMLParser.java:4546)
	at ptolemy.moml.MoMLParser.access$5(MoMLParser.java:4545)
	at ptolemy.moml.MoMLParser$DeleteRequest.execute(MoMLParser.java:7182)
	at ptolemy.moml.MoMLParser._processPendingRequests(MoMLParser.java:6339)
	at ptolemy.moml.MoMLParser.endElement(MoMLParser.java:893)
	at com.microstar.xml.XmlParser.parseETag(XmlParser.java:1026)
	at com.microstar.xml.XmlParser.parseContent(XmlParser.java:1098)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:924)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1403)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1375)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1531)
	at ptolemy.moml.MoMLChangeRequest._execute(MoMLChangeRequest.java:270)
	at ptolemy.kernel.util.ChangeRequest.execute(ChangeRequest.java:171)
	at ptolemy.kernel.util.NamedObj.executeChangeRequests(NamedObj.java:732)
	at ptolemy.kernel.util.NamedObj.requestChange(NamedObj.java:1756)
	at ptolemy.actor.CompositeActor.requestChange(CompositeActor.java:1521)
	at org.kepler.gui.KeplerGraphFrame.delete(KeplerGraphFrame.java:1015)
	at org.kepler.gui.KeplerGraphFrame$1.actionPerformed(KeplerGraphFrame.java:224)
	at javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3230)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1573)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2766)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2812)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2729)
	at java.awt.Component.processEvent(Component.java:5379)
	at java.awt.Container.processEvent(Container.java:2010)
	at java.awt.Component.dispatchEventImpl(Component.java:4068)
	at java.awt.Container.dispatchEventImpl(Container.java:2068)
	at java.awt.Component.dispatchEvent(Component.java:3903)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1828)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:681)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:940)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:810)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:645)
	at java.awt.Component.dispatchEventImpl(Component.java:3941)
	at java.awt.Container.dispatchEventImpl(Container.java:2068)
	at java.awt.Window.dispatchEventImpl(Window.java:1801)
	at java.awt.Component.dispatchEvent(Component.java:3903)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:176)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)

**Comment by cxbrooks** [comment]
I'll take a look since it looks like a Kepler issue. I wonder if KeplerGraphFrame's delete() override just needs to be updated to use BasicGraphFrame's _delete, or something along those lines.

**Comment by cxbrooks** [comment]
fixed in kepler r22595.
