### ISSUE TITLE
SetVariable sometimes causes a dependency loop exception to be thrown under PN

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#203]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#321
From: @cxbrooks
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Created attachment 31
SetVariable PN model that sometimes throws a dependency loop exception

If dynarray_expr_comp3.xml is run over and over again, eventually
an exception will appear:

ptolemy.kernel.util.IllegalActionException: Expression invalid.
  in .dynarray_expr_comp3.A.Expression
Because:
There is a dependency loop where .dynarray_expr_comp3.A.a directly or indirectly refers to itself in its expression: (j==1 ? {x} : {x,y})
	at ptolemy.actor.lib.Expression.fire(Expression.java:232)
	at ptolemy.actor.process.ProcessThread.run(ProcessThread.java:217)
Caused by: ptolemy.kernel.util.IllegalActionException: There is a dependency loop where .dynarray_expr_comp3.A.a directly or indirectly refers to itself in its expression: (j==1 ? {x} : {x,y})
	at ptolemy.data.expr.Variable._evaluate(Variable.java:1624)
	at ptolemy.data.expr.Variable.getToken(Variable.java:578)
	at ptolemy.actor.lib.Expression$VariableScope.get(Expression.java:336)
	at ptolemy.data.expr.ParseTreeEvaluator.visitLeafNode(ParseTreeEvaluator.java:652)
	at ptolemy.data.expr.ASTPtLeafNode.visit(ASTPtLeafNode.java:125)
	at ptolemy.data.expr.ParseTreeEvaluator.evaluateParseTree(ParseTreeEvaluator.java:104)
	at ptolemy.actor.lib.Expression.fire(Expression.java:227)
	... 1 more
Caused by: ptolemy.kernel.util.IllegalActionException: There is a dependency loop where .dynarray_expr_comp3.A.a directly or indirectly refers to itself in its expression: (j==1 ? {x} : {x,y})
	at ptolemy.data.expr.Variable._evaluate(Variable.java:1624)
	at ptolemy.data.expr.Variable.getToken(Variable.java:578)
	at ptolemy.actor.lib.Expression$VariableScope.get(Expression.java:336)
	at ptolemy.data.expr.ParseTreeEvaluator.visitLeafNode(ParseTreeEvaluator.java:652)
	at ptolemy.data.expr.ASTPtLeafNode.visit(ASTPtLeafNode.java:125)
	at ptolemy.data.expr.ParseTreeEvaluator.evaluateParseTree(ParseTreeEvaluator.java:104)
	at ptolemy.actor.lib.Expression.fire(Expression.java:227)
	at ptolemy.actor.process.ProcessThread.run(ProcessThread.java:217)

It looks to me like the exception that I was getting is because the
SetVariable actor is causing evaluation to occur in A.a.

SetVariable sets the parameter j.  The parameter A.a is set to
(j==1 ? {x} : {x,y})

I added a println to Variable._evaluate that prints a stack trace
when _dependencyLoop is set to true and the name of the Variable ends
with "A.a""

        // If _dependencyLoop is true, then this call to evaluate() must
        // have been triggered by evaluating the expression of this variable,
        // which means that the expression directly or indirectly refers
        // to itself.
        if (_dependencyLoop) {
            _dependencyLoop = false;
            throw new IllegalActionException("There is a dependency loop"
                    + " where " + getFullName() + " directly or indirectly"
                    + " refers to itself in its expression: "
                    + _currentExpression);
        }
        if (this.getFullName().endsWith("A.a")) {
            new Exception("Setting _dependencyLoop to true " + Thread.currentThread()).printStackTrace();
        }
        _dependencyLoop = true;

If I run the model over and over again, I eventually get the stack trace
that I reported below and that is in the code above.

The output looks like:

java.lang.Exception: Setting _dependencyLoop to true Thread[.dynarray_expr_comp3.Variable Setter,1,main]
    at ptolemy.data.expr.Variable._evaluate(Variable.java:1630)
    at ptolemy.data.expr.Variable._propagate(Variable.java:1734)
    at ptolemy.data.expr.Variable._propagateToValueListeners(Variable.java:1806)
    at ptolemy.data.expr.Variable._propagate(Variable.java:1765)
    at ptolemy.data.expr.Variable.validate(Variable.java:1430)
    at ptolemy.actor.lib.SetVariable._setValue(SetVariable.java:397)
    at ptolemy.actor.lib.SetVariable.fire(SetVariable.java:194)
    at ptolemy.actor.process.ProcessThread.run(ProcessThread.java:217)
java.lang.Exception: Setting _dependencyLoop to true Thread[.dynarray_expr_comp3.Variable Setter,1,main]
    at ptolemy.data.expr.Variable._evaluate(Variable.java:1630)
    at ptolemy.data.expr.Variable._propagate(Variable.java:1734)
    at ptolemy.data.expr.Variable._propagateToValueListeners(Variable.java:1806)
    at ptolemy.data.expr.Variable._propagate(Variable.java:1765)
    at ptolemy.data.expr.Variable.validate(Variable.java:1430)
    at ptolemy.actor.lib.SetVariable._setValue(SetVariable.java:397)
    at ptolemy.actor.lib.SetVariable.fire(SetVariable.java:194)
    at ptolemy.actor.process.ProcessThread.run(ProcessThread.java:217)

So, what I think is happening is that SetVariable is causing problems under PN.
I'm not surprised, SetVariable always frightens me, so I'm moving on.

Edward suggested setting SetVariable.delayed to true.  This avoid the exception
but the output is now

{"a string", "another string"}
{"a string", "another string"}

instead of alternating between

{"a string"}
{"a string", "another string"}

and

{"a string", "another string"}
{"a string", "another string"}

in a non-deterministic manner.

> Attached file: [dynarray_expr_comp3.xml](https://coq.inria.fr/bugfiles/attachment.cgi?id=31) (text/xml, 30961 bytes)
> Description:   SetVariable PN model that sometimes throws a dependency loop exception
