### ISSUE TITLE
IterateOverArray has a Configuration clone problem

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#204]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#322
From: @cxbrooks
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Created attachment 32
IterateOverArray Clone Bug

This is a strange bug that is probably a clone problems somewhere.

To replicate the bug:
1) Start up vergil with the attached file:
$PTII/bin/vergil IterateOverArrayCloneBug.xml

2) Help->About->Copyright
3) In the window that comes up:
   click on the "Other copyrights" link at the bottom
4) In the window that comes up:
   scroll down and click on "More information about this configuration"
5) In the window that comes up:
   click on "about:configuration" at the top

You will get a stack trace:

ptolemy.kernel.util.IllegalActionException: Attempt to link more than one relation to a single port.
  in .Z4.IterateOverArray.IterateComposite.RouteTable and .Z4.IterateOverArray.relation5
	at ptolemy.actor.IOPort._checkMultiportLink(IOPort.java:4179)
	at ptolemy.actor.IOPort._checkLink(IOPort.java:3588)
	at ptolemy.actor.TypedIOPort._checkLink(TypedIOPort.java:774)
	at ptolemy.kernel.ComponentPort.link(ComponentPort.java:544)
	at ptolemy.actor.IOPort.link(IOPort.java:2463)
	at ptolemy.actor.lib.hoc.MirrorComposite$2._execute(MirrorComposite.java:412)
	at ptolemy.kernel.util.ChangeRequest.execute(ChangeRequest.java:171)
	at ptolemy.kernel.util.NamedObj.executeChangeRequests(NamedObj.java:732)
	at ptolemy.kernel.util.NamedObj.requestChange(NamedObj.java:1757)
	at ptolemy.actor.CompositeActor.requestChange(CompositeActor.java:1533)
	at ptolemy.kernel.util.NamedObj.requestChange(NamedObj.java:1740)
	at ptolemy.actor.CompositeActor.requestChange(CompositeActor.java:1533)
	at ptolemy.actor.lib.hoc.MirrorComposite._addPort(MirrorComposite.java:424)
	at ptolemy.kernel.Port.setContainer(Port.java:621)
	at ptolemy.kernel.ComponentPort.setContainer(ComponentPort.java:584)
	at ptolemy.actor.IOPort.setContainer(IOPort.java:2953)
	at ptolemy.actor.lib.hoc.MirrorPort.setContainer(MirrorPort.java:147)
	at ptolemy.kernel.Entity.clone(Entity.java:174)
	at ptolemy.kernel.ComponentEntity.clone(ComponentEntity.java:124)
	at ptolemy.kernel.CompositeEntity.clone(CompositeEntity.java:324)
	at ptolemy.actor.CompositeActor.clone(CompositeActor.java:275)
	at ptolemy.actor.lib.hoc.MirrorComposite.clone(MirrorComposite.java:141)
	at ptolemy.actor.lib.hoc.IterateOverArray.clone(IterateOverArray.java:233)
	at ptolemy.kernel.CompositeEntity.clone(CompositeEntity.java:397)
	at ptolemy.actor.CompositeActor.clone(CompositeActor.java:275)
	at ptolemy.actor.gui.PtolemyEffigy.clone(PtolemyEffigy.java:140)
	at ptolemy.kernel.CompositeEntity.clone(CompositeEntity.java:397)
	at ptolemy.kernel.CompositeEntity.clone(CompositeEntity.java:397)
	at ptolemy.kernel.util.NamedObj.clone(NamedObj.java:409)
	at ptolemy.actor.gui.Configuration.check(Configuration.java:290)
	at ptolemy.actor.gui.HTMLAbout.hyperlinkUpdate(HTMLAbout.java:329)
	at ptolemy.actor.gui.HTMLViewer.hyperlinkUpdate(HTMLViewer.java:150)
	at javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:320)
	at javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:827)
	at javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:637)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:212)
	at java.awt.Component.processMouseEvent(Component.java:5605)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3129)
	at java.awt.Component.processEvent(Component.java:5367)
	at java.awt.Container.processEvent(Container.java:2010)
	at java.awt.Component.dispatchEventImpl(Component.java:4068)
	at java.awt.Container.dispatchEventImpl(Container.java:2068)
	at java.awt.Component.dispatchEvent(Component.java:3903)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4256)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3945)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3866)
	at java.awt.Container.dispatchEventImpl(Container.java:2054)
	at java.awt.Window.dispatchEventImpl(Window.java:1801)
	at java.awt.Component.dispatchEvent(Component.java:3903)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:176)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)


This example comes from the Wireless Zigbee model.

The odd thing is:  Why does calling Configuration.clone cause this problem.
Probably some fields in MirrorComposite is not getting cloned properly.

> Attached file: [IterateOverArrayCloneBug.xml](https://coq.inria.fr/bugfiles/attachment.cgi?id=32) (text/xml, 12878 bytes)
> Description:   IterateOverArray Clone Bug

**Comment by cxbrooks** [comment]
Created attachment 34
IterateOverArray model that uses Actor Oriented Classes that has a different result

> Attached file: [IterateOverArrayAOC.xml](https://coq.inria.fr/bugfiles/attachment.cgi?id=34) (text/xml, 47331 bytes)
> Description:   IterateOverArray model that uses Actor Oriented Classes that has a different result

**Comment by cxbrooks** [comment]
Using IterateOverArray in an ActorOrientedClass results in output
that is different from the same model without IterateOverArray being
in an ActorOrientedClass.

The model
$PTII/ptolemy/actor/lib/hoc/demo/IterateOverArray/IterateOverArray.xml
produces a nice pattern
If I convert the AntennaElements IterateOverArray actor to an
Actor Oriented Class, I get a circle as the output.

1) $PTII/bin/vergil ptolemy/actor/lib/hoc/demo/IterateOverArray/IterateOverArray.xml

2) Copy the AntennaElements actor, right click on the copy and select
"Convert To Class"

3) Right click on the Class definition and select Class Actions -> Create Instance

4) Hook up the new instance in place of the original AntennaElements actor

5) Run the model, you will get a circle?

See the attached for an example that uses a large section of the model
as an actor oriented class
