### ISSUE TITLE
Get Documentation on actor ports can give an NPE

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#209]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#327
From: Derik Barseghian &lt;<barseghian@nceas.ucsb.edu>&gt;
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Steps to reproduce:
Start vergil, drag a Const actor to canvas
Right click on input port, Documentation => Customize Documentation. Cancel.
Right click on input port, Documentation => Get Documentation. 

This gives a 'Cannot find an effigy...' Error popup, and an NPE on console:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ptolemy.vergil.basic.GetDocumentationAction.showDocAttributeTableau(GetDocumentationAction.java:421)
	at ptolemy.vergil.basic.GetDocumentationAction.showDocumentation(GetDocumentationAction.java:170)
	at ptolemy.vergil.basic.GetDocumentationAction.actionPerformed(GetDocumentationAction.java:120)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1882)

**Comment by cxbrooks** [comment]
I can reproduce this in the Ptolemy tree.
The problem is that right clicking on a port, customizing the documentation
and then viewing the documentation fails.

**Comment by cxbrooks** [comment]
Fixed by Edward.
I verified the fix in the Kepler trunk and 2.0 configuration.
