### ISSUE TITLE
ModularCodeGenTypedComposite inside TypedComposite fails because of Pub/Sub

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#222]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#340
From: @cxbrooks
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Created attachment 35
ModularCodeGen model that fails because it is inside a TypedComposite

Attached are two test cases, one that works, one that does not.
The difference is that the one that fails has a
ModularCodeGenTypedCompositeActor is inside a TypedComposteActor.

The stack trace is below.

I've been experimenting with modifying ModularCodeGenTypedComposite
so that when we create a relation, we set the width to 1, but that
does not seem to do it.

Error encountered in:
 <param name="channel" value="AnotherChannel"/>
 Cannot create receivers
  in .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite
 Because:
 The width of relation .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite.publisherRelation can not be uniquely inferrePlease make the width inference deterministic by explicitly specifying the width of this relation.
  in .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite.publisherRelation
 ptolemy.kernel.util.InternalErrorException: Cannot create receivers
  in .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite
 Because:
 The width of relation .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite.publisherRelation can not be uniquely inferrePlease make the width inference deterministic by explicitly specifying the width of this relation.
  in .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite.publisherRelation
 	at ptolemy.actor.CompositeActor.connectionsChanged(CompositeActor.java:355)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.connectionsChanged(ModularCodeGenTypedCompositeActor.java:214)
 	at ptolemy.kernel.ComponentPort._doLink(ComponentPort.java:1164)
 	at ptolemy.kernel.ComponentPort.liberalLink(ComponentPort.java:526)
 	at ptolemy.actor.IOPort.liberalLink(IOPort.java:2450)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.registerPublisherPort(ModularCodeGenTypedCompositeActor.java:920)
 	at ptolemy.actor.lib.Publisher.attributeChanged(Publisher.java:154)
 	at ptolemy.data.expr.Variable._setTokenAndNotify(Variable.java:1992)
 	at ptolemy.data.expr.Variable._evaluate(Variable.java:1646)
 	at ptolemy.data.expr.Variable._propagate(Variable.java:1732)
 	at ptolemy.data.expr.Variable.validate(Variable.java:1430)
 	at ptolemy.moml.MoMLParser.endDocument(MoMLParser.java:666)
 	at com.microstar.xml.XmlParser.doParse(XmlParser.java:162)
 	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
 	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1418)
 	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1374)
 	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1530)
 	at ptolemy.actor.LazyTypedCompositeActor.populate(LazyTypedCompositeActor.java:773)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.populate(ModularCodeGenTypedCompositeActor.java:782)
 	at ptolemy.actor.LazyTypedCompositeActor.deepEntityList(LazyTypedCompositeActor.java:337)
 	at ptolemy.actor.Director.wrapup(Director.java:1345)
 	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2021)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.wrapup(ModularCodeGenTypedCompositeActor.java:1072)
 	at ptolemy.actor.Director.wrapup(Director.java:1350)
 	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2021)
 	at ptolemy.actor.Manager.wrapup(Manager.java:1379)
 	at ptolemy.actor.Manager.execute(Manager.java:384)
 	at ptolemy.actor.Manager.run(Manager.java:1162)
 	at ptolemy.actor.Manager$3.run(Manager.java:1215)
 Caused by: ptolemy.kernel.util.IllegalActionException: The width of relation .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedposite.publisherRelation can not be uniquely inferred.
 Please make the width inference deterministic by explicitly specifying the width of this relation.
  in .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite.publisherRelation
 	at ptolemy.actor.RelationWidthInference.inferWidths(RelationWidthInference.java:388)
 	at ptolemy.actor.CompositeActor.inferWidths(CompositeActor.java:730)
 	at ptolemy.actor.IORelation.getWidth(IORelation.java:321)
 	at ptolemy.actor.IOPort.createReceivers(IOPort.java:619)
 	at ptolemy.actor.CompositeActor.connectionsChanged(CompositeActor.java:352)
 	... 28 more
 Caused by: ptolemy.kernel.util.IllegalActionException: The width of relation .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedposite.publisherRelation can not be uniquely inferred.
 Please make the width inference deterministic by explicitly specifying the width of this relation.
  in .ModularCodeGenPubSubAggLazy3SubH.CompositeActor.ModularCodeGenTypedComposite.publisherRelation
 	at ptolemy.actor.RelationWidthInference.inferWidths(RelationWidthInference.java:388)
 	at ptolemy.actor.CompositeActor.inferWidths(CompositeActor.java:730)
 	at ptolemy.actor.IORelation.getWidth(IORelation.java:321)
 	at ptolemy.actor.IOPort.createReceivers(IOPort.java:619)
 	at ptolemy.actor.CompositeActor.connectionsChanged(CompositeActor.java:352)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.connectionsChanged(ModularCodeGenTypedCompositeActor.java:214)
 	at ptolemy.kernel.ComponentPort._doLink(ComponentPort.java:1164)
 	at ptolemy.kernel.ComponentPort.liberalLink(ComponentPort.java:526)
 	at ptolemy.actor.IOPort.liberalLink(IOPort.java:2450)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.registerPublisherPort(ModularCodeGenTypedCompositeActor.java:920)
 	at ptolemy.actor.lib.Publisher.attributeChanged(Publisher.java:154)
 	at ptolemy.data.expr.Variable._setTokenAndNotify(Variable.java:1992)
 	at ptolemy.data.expr.Variable._evaluate(Variable.java:1646)
 	at ptolemy.data.expr.Variable._propagate(Variable.java:1732)
 	at ptolemy.data.expr.Variable.validate(Variable.java:1430)
 	at ptolemy.moml.MoMLParser.endDocument(MoMLParser.java:666)
 	at com.microstar.xml.XmlParser.doParse(XmlParser.java:162)
 	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
 	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1418)
 	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1374)
 	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1530)
 	at ptolemy.actor.LazyTypedCompositeActor.populate(LazyTypedCompositeActor.java:773)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.populate(ModularCodeGenTypedCompositeActor.java:782)
 	at ptolemy.actor.LazyTypedCompositeActor.deepEntityList(LazyTypedCompositeActor.java:337)
 	at ptolemy.actor.Director.wrapup(Director.java:1345)
 	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2021)
 	at ptolemy.cg.lib.ModularCodeGenTypedCompositeActor.wrapup(ModularCodeGenTypedCompositeActor.java:1072)
 	at ptolemy.actor.Director.wrapup(Director.java:1350)
 	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2021)
 	at ptolemy.actor.Manager.wrapup(Manager.java:1379)
 	at ptolemy.actor.Manager.execute(Manager.java:384)
 	at ptolemy.actor.Manager.run(Manager.java:1162)
 	at ptolemy.actor.Manager$3.run(Manager.java:1215)

> Attached file: [ModularCodeGenPubSubAggLazy3SubH.xml](https://coq.inria.fr/bugfiles/attachment.cgi?id=35) (text/xml, 13378 bytes)
> Description:   ModularCodeGen model that fails because it is inside a TypedComposite

**Comment by cxbrooks** [comment]
ModularCodeGen works inside a TypedComposite with Pub/Sub.

However
$PTII/bin/vergil $PTII/ptolemy/cg/lib/test/auto/ModularCodeGenLazyPubSubGlobal.xml
fails when opened and then run the first time.

The stack trace is
ptolemy.kernel.util.IllegalActionException: Failed to find a publisher to match "AnotherChan.*"
  in .ModularCodeGenLazyPubSubGlobal.SubscriptionAggregator
	at ptolemy.actor.CompositeActor.linkToPublishedPort(CompositeActor.java:1283)
	at ptolemy.actor.lib.SubscriptionAggregator._updateLinks(SubscriptionAggregator.java:236)
	at ptolemy.actor.lib.Subscriber.preinitialize(Subscriber.java:278)
	at ptolemy.actor.Director.preinitialize(Director.java:998)
	at ptolemy.actor.Director.preinitialize(Director.java:979)
	at ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:640)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1664)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:983)
	at ptolemy.actor.Manager.initialize(Manager.java:643)
	at ptolemy.actor.Manager.execute(Manager.java:340)
	at ptolemy.actor.Manager.run(Manager.java:1164)
	at ptolemy.actor.Manager$3.run(Manager.java:1217)

However, if the model is run the second time, then it works?


However, the model runs fine if I do:
1. $PTII/bin/vergil $PTII/ptolemy/cg/lib/test/auto/ModularCodeGenLazyPubSubGlobal.xml
2. Open the "CompositeActor"
3. Open the "ModularCodeGenTypedCompositeActor"
4. Hit the run button.

**Comment by cxbrooks** [comment]
Fixed by Dai!

I wrote:

> ModularCodeGen works inside a TypedComposite with Pub/Sub.
> >> 
> >> However
> >> $PTII/bin/vergil
> >> $PTII/ptolemy/cg/lib/test/auto/ModularCodeGenLazyPubSubGlobal.xml
> >> fails when opened and then run the first time.
> >> 
> >> The stack trace is
> >> ptolemy.kernel.util.IllegalActionException: Failed to find a publisher to match
> >> "AnotherChan.*"
> >>  in .ModularCodeGenLazyPubSubGlobal.SubscriptionAggregator
> >>    at
> >> ptolemy.actor.CompositeActor.linkToPublishedPort(CompositeActor.java:1283)
> >>    at
> >> ptolemy.actor.lib.SubscriptionAggregator._updateLinks(SubscriptionAggregator.java:236)
> >>    at ptolemy.actor.lib.Subscriber.preinitialize(Subscriber.java:278)
> >>    at ptolemy.actor.Director.preinitialize(Director.java:998)
> >>    at ptolemy.actor.Director.preinitialize(Director.java:979)
> >>    at
> >> ptolemy.domains.sdf.kernel.SDFDirector.preinitialize(SDFDirector.java:640)
> >>    at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1664)
> >>    at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:983)
> >>    at ptolemy.actor.Manager.initialize(Manager.java:643)
> >>    at ptolemy.actor.Manager.execute(Manager.java:340)
> >>    at ptolemy.actor.Manager.run(Manager.java:1164)
> >>    at ptolemy.actor.Manager$3.run(Manager.java:1217)
> >> 
> >> However, if the model is run the second time, then it works?
> >> 
> >> 
> >> However, the model runs fine if I do:
> >> 1. $PTII/bin/vergil
> >> $PTII/ptolemy/cg/lib/test/auto/ModularCodeGenLazyPubSubGlobal.xml
> >> 2. Open the "CompositeActor"
> >> 3. Open the "ModularCodeGenTypedCompositeActor"
> >> 4. Hit the run button.
>
