### ISSUE TITLE
Modular Codegen models that have Pub/Subs with widths other than 1 have problems

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#228]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#346
From: @cxbrooks
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
I've see problmes with Modular Codegen pub/sub models that have a Publisher
with multiple Subscribers outside the ModularCodeGenTypedAtomicActor.

We need some test cases that illustrate this common scenario.

**Comment by cxbrooks** [comment]
$PTII/bin/vergil /Users/cxh/ptII/ptolemy/cg/lib/test/auto/PubSubAggTypedCompositeWidth2.xml
fails with
ptolemy.actor.TypeConflictException: Types resolved to unacceptable types in .PubSubAggTypedCompositeWidth2 due to the following inequalities:
  (ptolemy.actor.TypedIOPort {.PubSubAggTypedCompositeWidth2.CompositeActor.SubscriptionAggregator2.input}, unknown) <= (ptolemy.actor.TypedIOPort {.PubSubAggTypedCompositeWidth2.CompositeActor.SubscriptionAggregator2.output}, unknown)
  (ptolemy.actor.TypedIOPort {.PubSubAggTypedCompositeWidth2.CompositeActor.SubscriptionAggregator2.output}, unknown) <= (ptolemy.actor.TypedIOPort {.PubSubAggTypedCompositeWidth2.CompositeActor.Test2.input}, unknown)

	at ptolemy.actor.TypedCompositeActor.resolveTypes(TypedCompositeActor.java:324)
	at ptolemy.actor.Manager.resolveTypes(Manager.java:1113)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:995)
	at ptolemy.actor.Manager.initialize(Manager.java:643)
	at ptolemy.actor.Manager.execute(Manager.java:340)
	at ptolemy.actor.Manager.run(Manager.java:1164)
	at ptolemy.actor.Manager$3.run(Manager.java:1217)

**Comment by cxbrooks** [comment]
Fixed by Dai!
