### ISSUE TITLE
Layout cannot be run a second time on a GT model

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#229]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#347
From: @cxbrooks
Reported version: 8.1.devel
CC:   huining.feng@gmail.com, pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
1. cd $PTII/ptolemy/actor/gt/demo/DiningPhilosophers
2. vergil DiningPhilosophers.xml
3. run the model
4. do layout on the result
5. try to do layout again on the result. 

The problem is that findEffigy() is returning a KeilerLayoutGUI instead
of the ActorGraphFrame.

The workaround is to save the model.  I added a better error message
that says to save the model.

The problem appears to be associated with gt and ModelView.  If I create
a model by hand and don't save it, then layout works fine.

**Comment by cxbrooks** [comment]
Fixed. Originally I reset MoML parser every time AFTER cleaning up model in the View event. The bug disappears when I change the code to reset MoML parser every time BEFORE cleaning up model. Reason unclear.

**Comment by cxbrooks** [comment]
Hmm, this bug still occurs for me:

1. cd $PTII/ptolemy/actor/gt/demo/DiningPhilosophers
2. vergil DiningPhilosophers.xml
3. run the model
4. do layout on the resulting model
5. try to do layout again on the resulting model

The stack trace below appears:

ptolemy.kernel.util.InternalErrorException: For now only actor oriented graphs with ports are supported by KIELER layout. Internal Error: findEffigy() returned a KielerLayoutGUI, please save the model before running the layout mechanism.
  in .DiningPhilosophers
	at ptolemy.vergil.basic.layout.KielerLayoutGUI$BaseLayoutAction.actionPerformed(KielerLayoutGUI.java:255)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1882)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2202)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:420)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:258)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:231)
	at java.awt.Component.processMouseEvent(Component.java:5602)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3129)
	at java.awt.Component.processEvent(Component.java:5367)
	at java.awt.Container.processEvent(Container.java:2010)
	at java.awt.Component.dispatchEventImpl(Component.java:4068)
	at java.awt.Container.dispatchEventImpl(Container.java:2068)
	at java.awt.Component.dispatchEvent(Component.java:3903)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4256)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3936)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3866)
	at java.awt.Container.dispatchEventImpl(Container.java:2054)
	at java.awt.Window.dispatchEventImpl(Window.java:1801)
	at java.awt.Component.dispatchEvent(Component.java:3903)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:176)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)

**Comment by cxbrooks** [comment]
This is fixed, I can run layout more than once in a model generated by GT.
