### ISSUE TITLE
NullPointerError on renaming

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#235]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#355
From: Ben Lickly &lt;<blickly@eecs.berkeley.edu>&gt;
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Vergil seems to now have a bug causing NullPointerErrors to be thrown when an actor is renamed.

The bug is non-deterministic, but on my system, usually 2 or 3 renamings (either of the same actor multiple times or of different actors) is enough to trigger the bug 

Steps to reproduce:
1. Open a new model.
2. Drag in an actor (or an entity or an attribute).
3. Select the actor
4. Open the rename dialog with F2.
5. Give the actor a new name.
6. Repeat steps 3-5.

Exception text:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ptolemy.actor.gui.RenameConfigurer.apply(RenameConfigurer.java:199)
	at ptolemy.actor.gui.RenameDialog._handleClosing(RenameDialog.java:69)
	at ptolemy.gui.ComponentDialog$1.propertyChange(ComponentDialog.java:214)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:339)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:276)
	at java.awt.Component.firePropertyChange(Component.java:8217)
	at javax.swing.JOptionPane.setValue(JOptionPane.java:1945)
	at javax.swing.plaf.basic.BasicOptionPaneUI$ButtonActionListener.actionPerformed(BasicOptionPaneUI.java:1187)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
	at java.awt.Component.processMouseEvent(Component.java:6352)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6117)
	at java.awt.Container.processEvent(Container.java:2085)
	at java.awt.Component.dispatchEventImpl(Component.java:4714)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4621)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4282)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4212)
	at java.awt.Container.dispatchEventImpl(Container.java:2129)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:635)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1046)
	at java.awt.Dialog$3.run(Dialog.java:1098)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1096)
	at java.awt.Component.show(Component.java:1563)
	at java.awt.Component.setVisible(Component.java:1515)
	at java.awt.Window.setVisible(Window.java:842)
	at java.awt.Dialog.setVisible(Dialog.java:986)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:255)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:122)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:101)
	at ptolemy.actor.gui.RenameDialog.<init>(RenameDialog.java:57)
	at ptolemy.vergil.kernel.RenameDialogAction.actionPerformed(RenameDialogAction.java:113)
	at javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3368)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1639)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2851)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:267)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:216)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2928)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2920)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2814)
	at java.awt.Component.processEvent(Component.java:6129)
	at java.awt.Container.processEvent(Container.java:2085)
	at java.awt.Component.dispatchEventImpl(Component.java:4714)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1850)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:712)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:990)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:855)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:676)
	at java.awt.Component.dispatchEventImpl(Component.java:4586)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:635)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by cxbrooks** [comment]
I think the problem here is that F2 on the canvas will throw a NPE.
Steps to reproduce:
1. Open a new model.
2. Open the rename dialog with F2.
3. Give the actor a new name.

I get the following exception in stdout:

 Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ptolemy.actor.gui.RenameConfigurer.apply(RenameConfigurer.java:199)
	at ptolemy.actor.gui.RenameDialog._handleClosing(RenameDialog.java:69)
	at ptolemy.gui.ComponentDialog$1.propertyChange(ComponentDialog.java:214)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:339)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:276)
	at java.awt.Component.firePropertyChange(Component.java:8217)
	at javax.swing.JOptionPane.setValue(JOptionPane.java:1945)
	at javax.swing.plaf.basic.BasicOptionPaneUI$ButtonActionListener.actionPerformed(BasicOptionPaneUI.java:1187)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
	at java.awt.Component.processMouseEvent(Component.java:6352)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6117)
	at java.awt.Container.processEvent(Container.java:2085)
	at java.awt.Component.dispatchEventImpl(Component.java:4714)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4621)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4282)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4212)
	at java.awt.Container.dispatchEventImpl(Container.java:2129)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:635)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1046)
	at java.awt.Dialog$3.run(Dialog.java:1098)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1096)
	at java.awt.Component.show(Component.java:1563)
	at java.awt.Component.setVisible(Component.java:1515)
	at java.awt.Window.setVisible(Window.java:842)
	at java.awt.Dialog.setVisible(Dialog.java:986)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:255)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:122)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:101)
	at ptolemy.actor.gui.RenameDialog.<init>(RenameDialog.java:57)
	at ptolemy.vergil.kernel.RenameDialogAction.actionPerformed(RenameDialogAction.java:113)
	at javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3368)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1639)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2851)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:267)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:216)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2928)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2920)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2814)
	at java.awt.Component.processEvent(Component.java:6129)
	at java.awt.Container.processEvent(Container.java:2085)
	at java.awt.Component.dispatchEventImpl(Component.java:4714)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1850)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:712)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:990)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:855)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:676)
	at java.awt.Component.dispatchEventImpl(Component.java:4586)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:635)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)



The offending line in actor.gui.RenameConfigurer is:
         parent.requestChange(request);

parent gets set earlier

         NamedObj parent = _object.getContainer();


So what is happening is that there is no parent for the open composite,
so parent is set to null.

As a hack, I tried to use _object instead parent:

            NamedObj context = parent;
            if (context == null) {
                context = _object;
            }
            MoMLChangeRequest request = new MoMLChangeRequest(this, // originator
                    context, // context
                    moml.toString(), // MoML code
                    null); // base
            request.addChangeListener(this);
            request.setUndoable(true);
            context.requestChange(request);

But now I get

com.microstar.xml.XmlException: Cannot create entity without a class name. in [external stream] at line 1 and column 19
	at ptolemy.moml.MoMLParser._checkForNull(MoMLParser.java:3792)
	at ptolemy.moml.MoMLParser._createEntity(MoMLParser.java:3973)
	at ptolemy.moml.MoMLParser.startElement(MoMLParser.java:2493)
	at com.microstar.xml.XmlParser.parseElement(XmlParser.java:921)
	at com.microstar.xml.XmlParser.parseDocument(XmlParser.java:481)
	at com.microstar.xml.XmlParser.doParse(XmlParser.java:159)
	at com.microstar.xml.XmlParser.parse(XmlParser.java:132)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1402)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1374)
	at ptolemy.moml.MoMLParser.parse(MoMLParser.java:1530)
	at ptolemy.moml.MoMLChangeRequest._execute(MoMLChangeRequest.java:289)
	at ptolemy.kernel.util.ChangeRequest.execute(ChangeRequest.java:171)
	at ptolemy.kernel.util.NamedObj.executeChangeRequests(NamedObj.java:735)
	at ptolemy.kernel.util.NamedObj.requestChange(NamedObj.java:1775)
	at ptolemy.actor.CompositeActor.requestChange(CompositeActor.java:1921)
	at ptolemy.actor.gui.RenameConfigurer.apply(RenameConfigurer.java:202)
	at ptolemy.actor.gui.RenameDialog._handleClosing(RenameDialog.java:69)
	at ptolemy.gui.ComponentDialog$1.propertyChange(ComponentDialog.java:214)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:339)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:276)
	at java.awt.Component.firePropertyChange(Component.java:8217)
	at javax.swing.JOptionPane.setValue(JOptionPane.java:1945)
	at javax.swing.plaf.basic.BasicOptionPaneUI$ButtonActionListener.actionPerformed(BasicOptionPaneUI.java:1187)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
	at java.awt.Component.processMouseEvent(Component.java:6352)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6117)
	at java.awt.Container.processEvent(Container.java:2085)
	at java.awt.Component.dispatchEventImpl(Component.java:4714)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4621)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4282)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4212)
	at java.awt.Container.dispatchEventImpl(Container.java:2129)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:635)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1046)
	at java.awt.Dialog$3.run(Dialog.java:1098)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1096)
	at java.awt.Component.show(Component.java:1563)
	at java.awt.Component.setVisible(Component.java:1515)
	at java.awt.Window.setVisible(Window.java:842)
	at java.awt.Dialog.setVisible(Dialog.java:986)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:255)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:122)
	at ptolemy.gui.ComponentDialog.<init>(ComponentDialog.java:101)
	at ptolemy.actor.gui.RenameDialog.<init>(RenameDialog.java:57)
	at ptolemy.vergil.kernel.RenameDialogAction.actionPerformed(RenameDialogAction.java:113)
	at javax.swing.JComponent$ActionStandin.actionPerformed(JComponent.java:3368)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1639)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2851)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:267)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:216)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2928)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2920)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2814)
	at java.awt.Component.processEvent(Component.java:6129)
	at java.awt.Container.processEvent(Container.java:2085)
	at java.awt.Component.dispatchEventImpl(Component.java:4714)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1850)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:712)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:990)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:855)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:676)
	at java.awt.Component.dispatchEventImpl(Component.java:4586)
	at java.awt.Container.dispatchEventImpl(Container.java:2143)
	at java.awt.Window.dispatchEventImpl(Window.java:2478)
	at java.awt.Component.dispatchEvent(Component.java:4544)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:635)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)



One interesting thing is that the rename context menu is not visible
on the canvas.  In other words, right clicking on the canvas in Ptolemy
brings up a menu that does not have a rename menu choice.  What is happening
here is that F2 is invoking the rename action on the top level composite.

Kepler does have a rename menu choice for the top level.  However, it 
produces a similar stack trace.   See also the Kepler bug
Composite Actor windows show wrong title after workflow Rename
http://bugzilla.ecoinformatics.org/show_bug.cgi?id=5101

**Comment by cxbrooks** [comment]
Fixed.
I think the problem is that hitting F2 in an unnamed model was
bringing up a NPE.  We now tell the user to save the model.
