### ISSUE TITLE
SynthesizedVoice throws an Actor is not ready to fire exception at the end

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#239]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#359
From: @cxbrooks
Reported version: 8.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Under Linux and Windows 7,  

http://ptolemy.eecs.berkeley.edu/ptolemyII/ptII8.0/ptII/ptolemy/domains/sdf/demo/SynthesizedVoice/SynthesizedVoice.jnlp

sometimes throws the following exception at the end.

ptolemy.kernel.util.IllegalActionException: Actor is not ready to fire.  Perhaps VariableRecursiveLattice.prefire() returned false? Try debugging the actor by selecting "Listen to Actor".  Also, for SDF check moml for tokenConsumptionRate on input.
  in .SynthesizedVoice.SDF Director and .SynthesizedVoice.VariableRecursiveLattice
at ptolemy.actor.sched.StaticSchedulingDirector.fire(StaticSchedulingDirector.java:194)
at ptolemy.actor.CompositeActor.fire(CompositeActor.java:458)
at ptolemy.actor.Manager.iterate(Manager.java:749)
at ptolemy.actor.Manager.execute(Manager.java:351)
at ptolemy.actor.Manager.run(Manager.java:1164)
at ptolemy.actor.Manager$3.run(Manager.java:1217)


Also, it looks like the model is repeatedly resolving types.
