### ISSUE TITLE
Opening a model from File->Recent Files occasionally results in an error.

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#312]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#514
From: @lhstrh
Reported version: 9.1.devel
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
Not sure of the precondition, the error is not always thrown.
Error message: "Error reading <file> No associated Tableau! Can't open a file."
Stack trace:
java.lang.Exception: No associated Tableau! Can't open a file.
	at ptolemy.actor.gui.TableauFrame._read(TableauFrame.java:1034)
	at ptolemy.gui.Top$HistoryMenuListener.actionPerformed(Top.java:1973)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by cxbrooks** [comment]
Not able to reproduce anymore, assuming this is fixed.

**Comment by cxbrooks** [comment]
I agree that this is not reproducible, so I'm changing it to "Resolved" -> "Worksforme".

I took a quick look at this and it looks like the error is thrown if the _tableau in TableauFrame is null.  One way to set _tableau to null is from the TableauFrame constructor.  Another way is that TableauFrame.setTableau() could be called with a null argument.  TableauFrame.dispose() calls setTableau(null).

The only way I can see this happening is if there is a TableauFrame that somehow has a null _tableau, either by construction or by calling dispose().

Anyway, this seems unlikely, and as we have not had other reports of this problem, closing it is the correct thing to do.
