### ISSUE TITLE
SaveAs: "save submodel only" does not work with modal models

### ISSUE THREAD

**Issue by cxbrooks** [cxbrooks/test#50]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#53
From: @cxbrooks
Reported version: 6.0.1
CC:   pt-dev@chess.eecs.berkeley.edu

**Comment by cxbrooks** [comment]
If I have a model model and do "Save As" and select "save submodel only"
then I get a null pointer exception:
java.lang.NullPointerException
	at ptolemy.domains.fsm.kernel.State.getRefinement(State.java:281)
	at ptolemy.vergil.fsm.StateIcon._getFill(StateIcon.java:88)
	at ptolemy.vergil.icon.NameIcon.createBackgroundFigure(NameIcon.java:172)
	at ptolemy.vergil.icon.EditorIcon.createFigure(EditorIcon.java:293)
	at ptolemy.vergil.icon.NameIcon.createFigure(NameIcon.java:183)
	at
ptolemy.vergil.fsm.StateController$StateRenderer.render(StateController.java:285)
	at diva.graph.BasicNodeController._renderNode(BasicNodeController.java:281)
	at
ptolemy.vergil.basic.LocatableNodeController._renderNode(LocatableNodeController.java:240)
	at diva.graph.BasicNodeController.drawNode(BasicNodeController.java:177)
	at
ptolemy.vergil.basic.LocatableNodeController.drawNode(LocatableNodeController.java:98)
	at diva.graph.AbstractGraphController.drawNode(AbstractGraphController.java:191)
	at diva.graph.AbstractGraphController.rerender(AbstractGraphController.java:373)
	at
diva.graph.AbstractGraphController$ChangeListener.structureChanged(AbstractGraphController.java:638)
	at
diva.graph.AbstractGraphController.setGraphModel(AbstractGraphController.java:504)
	at diva.graph.GraphPane.<init>(GraphPane.java:63)
	at ptolemy.vergil.fsm.FSMGraphFrame._createGraphPane(FSMGraphFrame.java:175)
	at
ptolemy.vergil.basic.BasicGraphFrame._createRightComponent(BasicGraphFrame.java:1467)
	at ptolemy.vergil.basic.BasicGraphFrame.<init>(BasicGraphFrame.java:200)
	at ptolemy.vergil.basic.ExtendedGraphFrame.<init>(ExtendedGraphFrame.java:95)
	at ptolemy.vergil.fsm.FSMGraphFrame.<init>(FSMGraphFrame.java:100)
	at ptolemy.vergil.fsm.FSMGraphTableau.createGraphFrame(FSMGraphTableau.java:119)
	at ptolemy.vergil.fsm.FSMGraphTableau.<init>(FSMGraphTableau.java:92)
	at
ptolemy.vergil.fsm.FSMGraphTableau$Factory.createTableau(FSMGraphTableau.java:173)
	at
ptolemy.actor.gui.PtolemyTableauFactory.createTableau(PtolemyTableauFactory.java:100)
	at ptolemy.actor.gui.TableauFactory.createTableau(TableauFactory.java:122)
	at ptolemy.actor.gui.Configuration.createPrimaryTableau(Configuration.java:333)
	at ptolemy.actor.gui.Configuration.openModel(Configuration.java:626)
	at ptolemy.actor.gui.Configuration.openModel(Configuration.java:547)
	at ptolemy.actor.gui.TableauFrame._saveAs(TableauFrame.java:896)
	at ptolemy.actor.gui.PtolemyFrame._saveAs(PtolemyFrame.java:290)
	at ptolemy.gui.Top$FileMenuListener.actionPerformed(Top.java:1030)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1849)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2169)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:420)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:258)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:302)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1000)
	at
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1041)
	at java.awt.Component.processMouseEvent(Component.java:5488)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3126)
	at java.awt.Component.processEvent(Component.java:5253)
	at java.awt.Container.processEvent(Container.java:1966)

1. Start up vergil 6.1.devel
2. File -> New -> Graph Editor
3. Click Utilities, then drag the model model icon in
4. Look inside the modal model, drag in a state icon
5. Click File -> Save As, click on the "save submodel only" icon.
6. You will get a NullPointerException.

**Comment by cxbrooks** [comment]
My change to fsm/kernel/State.java fixes this bug and save submodel now works
with ModalBSC.
